import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import BootstrapClient from "@/components/BootstrapClient";
import "./globals.css";
import Navbarpage from "@/components/Navbar";
import PageTransition from "@/components/Pagetransition";
import { ThemeProvider } from "@/components/Themeprovider";
import ThemeWrapper from "@/components/Themewrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Anna Market",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > 
        <BootstrapClient />
         <ThemeWrapper>
          <PageTransition>
            <Navbarpage />
            {children}
          </PageTransition>
         </ThemeWrapper>
      </body>
    </html>
  );
}
